#!/bin/bash
# Upscaler Launcher - Opens Terminal to run the setup script
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)/Resources"
osascript -e "tell application \"Terminal\" to do script \"'$SCRIPT_DIR/run.sh'\""





